{
  "openapi": "3.0.0",
  "info": {
    "title": "Neighbors REST API",
    "version": "2.0",
    "license": {
      "name": "Ex",
      "url": "www.example.com"
    },
    "description": "Ex",
    "contact": {
      "url": "www.example.com",
      "name": "Ex",
      "email": "sample@example.com"
    },
    "termsOfService": "www.example.com"
  },
  "servers": [
    {
      "url": "https://neighbors.evolbio.mpg.de/api/v2",
      "description": ""
    }
  ],
  "tags": [
    {
      "name": "Accession",
      "description": "Provides data primarily tied to Accessions e.g. the accessions level."
    },
    {
      "name": "Taxon",
      "description": "Provides data contextually tied to Taxa e.g. a taxons parent."
    }
  ],
  "paths": {
    "/accessions": {
      "get": {
        "summary": "Get accession levels",
        "tags": [
          "Accession"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Accession"
                  }
                },
                "examples": {
                  "Example": {
                    "value": [
                      {
                        "accession": "GCF_000001405.40",
                        "level": "chromosome"
                      },
                      {
                        "accession": "GCA_000002115.2",
                        "level": "chromosome"
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Missing required parameter."
          }
        },
        "operationId": "get-accessions",
        "parameters": [
          {
            "schema": {
              "type": "array",
              "example": [
                "GCF_000001405.40",
                "GCA_000002115.2"
              ],
              "items": {
                "type": "string"
              }
            },
            "in": "query",
            "name": "accession_ids",
            "description": "IDs of accessions to filter for",
            "explode": false,
            "style": "form",
            "required": true
          },
          {
            "$ref": "#/components/parameters/page"
          },
          {
            "$ref": "#/components/parameters/page_size"
          }
        ],
        "description": "Get accessions and their levels filtered by accession IDs"
      }
    },
    "/assembly-levels": {
      "get": {
        "summary": "Get all assembly levels",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "examples": {
                  "Example": {
                    "value": [
                      "complete",
                      "chromosome",
                      "scaffold",
                      "contig"
                    ]
                  }
                }
              }
            }
          }
        },
        "operationId": "get-general-assembly-levels",
        "description": "Get all possible assembly levels",
        "tags": [
          "Accession"
        ]
      },
      "parameters": []
    },
    "/ranks": {
      "get": {
        "summary": "Get ranks of taxa",
        "tags": [
          "Taxon"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Rank"
                  }
                },
                "examples": {
                  "Example": {
                    "value": [
                      {
                        "tax_id": 9606,
                        "rank": "species"
                      },
                      {
                        "tax_id": 9605,
                        "rank": "genus"
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Missing required parameter."
          }
        },
        "operationId": "get-ranks",
        "parameters": [
          {
            "schema": {
              "type": "array",
              "example": [
                9606,
                9605
              ],
              "items": {
                "type": "integer"
              }
            },
            "in": "query",
            "name": "taxon_ids",
            "description": "IDs of taxa to filter for",
            "explode": false,
            "style": "form",
            "required": true
          },
          {
            "$ref": "#/components/parameters/page"
          },
          {
            "$ref": "#/components/parameters/page_size"
          }
        ],
        "description": "Get ranks of taxa filtered by taxon IDs"
      }
    },
    "/taxa": {
      "get": {
        "summary": "Get taxa by name",
        "tags": [
          "Taxon"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Taxon"
                  }
                },
                "examples": {
                  "Example": {
                    "value": [
                      {
                        "taxid": 103600,
                        "parent": 103599,
                        "name": "Sousa chinensis",
                        "common_name": "Indo-pacific humpbacked dolphin"
                      },
                      {
                        "taxid": 9737,
                        "parent": 9734,
                        "name": "Stenella coeruleoalba",
                        "common_name": "striped dolphin"
                      },
                      {
                        "taxid": 79784,
                        "parent": 9738,
                        "name": "Tursiops aduncus",
                        "common_name": "Indo-pacific bottlenose dolphin"
                      },
                      {
                        "taxid": 34814,
                        "parent": 13453,
                        "name": "Coryphaena hippurus",
                        "common_name": "common dolphinfish"
                      },
                      {
                        "taxid": 27766,
                        "parent": 1489907,
                        "name": "Coryphaenidae",
                        "common_name": "dolphinfishes"
                      },
                      {
                        "taxid": 118797,
                        "parent": 118796,
                        "name": "Lipotes vexillifer",
                        "common_name": "Yangtze River dolphin"
                      },
                      {
                        "taxid": 48752,
                        "parent": 48750,
                        "name": "Platanista minor",
                        "common_name": "Indus River dolphin"
                      },
                      {
                        "taxid": 3371155,
                        "parent": 3371042,
                        "name": "Sagmatias obliquidens",
                        "common_name": "Pacific white-sided dolphin"
                      },
                      {
                        "taxid": 46167,
                        "parent": 46166,
                        "name": "Steno bredanensis",
                        "common_name": "rough-toothed dolphin"
                      },
                      {
                        "taxid": 103582,
                        "parent": 27607,
                        "name": "Cephalorhynchus commersonii",
                        "common_name": "Commerson's dolphin"
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Missing required parameter."
          }
        },
        "operationId": "get-taxa",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "example": "dolph"
            },
            "in": "query",
            "name": "name",
            "description": "Name or pattern of the taxa",
            "required": true
          },
          {
            "schema": {
              "type": "boolean"
            },
            "in": "query",
            "name": "scientific",
            "description": "Whether to search in scientific names only"
          },
          {
            "schema": {
              "type": "boolean"
            },
            "in": "query",
            "name": "exact",
            "description": "Whether to search for exactly that name or use the name as a pattern"
          },
          {
            "schema": {
              "type": "integer",
              "example": 2,
              "default": 0,
              "minimum": 0
            },
            "in": "query",
            "name": "page",
            "description": "Current page"
          },
          {
            "schema": {
              "type": "integer",
              "example": 10,
              "default": -1,
              "minimum": -1
            },
            "in": "query",
            "name": "page_size",
            "description": "Amount of entries per page"
          }
        ],
        "description": "Get basic taxon data for taxa with the given name"
      }
    },
    "/taxa-accessions": {
      "get": {
        "summary": "Get taxons accessions",
        "tags": [
          "Taxon"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/TaxonAccessions"
                  }
                },
                "examples": {
                  "Example": {
                    "value": [
                      {
                        "taxid": 278148,
                        "accessions": [
                          {
                            "accession": "GCF_001618845.1",
                            "level": "complete"
                          }
                        ]
                      },
                      {
                        "taxid": 602633,
                        "accessions": [
                          {
                            "accession": "GCA_003063835.1",
                            "level": "scaffold"
                          }
                        ]
                      },
                      {
                        "taxid": 765698,
                        "accessions": [
                          {
                            "accession": "GCF_000185905.1",
                            "level": "complete"
                          }
                        ]
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Missing required parameter."
          }
        },
        "operationId": "get-taxa-accessions",
        "description": "Get the accessions associated with taxa filtered by taxon IDs",
        "parameters": [
          {
            "schema": {
              "type": "array",
              "example": [
                278148,
                602633
              ],
              "items": {
                "type": "integer"
              }
            },
            "in": "query",
            "name": "taxon_ids",
            "description": "IDs of taxa to filter for",
            "explode": false,
            "style": "form",
            "required": true
          },
          {
            "$ref": "#/components/parameters/page"
          },
          {
            "$ref": "#/components/parameters/page_size"
          }
        ]
      }
    },
    "/taxa-count": {
      "parameters": [],
      "get": {
        "summary": "Get taxa count",
        "responses": {
          "200": {
            "description": "OK",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "num_taxa": {
                      "type": "integer"
                    }
                  }
                },
                "examples": {
                  "Example": {
                    "value": {
                      "num_taxa": 2739523
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "taxa-count",
        "description": "Get the number of taxa in the db",
        "tags": [
          "Taxon"
        ]
      }
    },
    "/taxa-info": {
      "get": {
        "summary": "Get taxa info",
        "tags": [
          "Taxon"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/TaxonInfo"
                  }
                },
                "examples": {
                  "Example": {
                    "value": [
                      {
                        "tax_id": 562,
                        "parent": 561,
                        "is_leaf": false,
                        "name": "Escherichia coli",
                        "common_name": "",
                        "rank": "species",
                        "raw_genome_counts": [
                          {
                            "level": "complete",
                            "count": 7233
                          },
                          {
                            "level": "chromosome",
                            "count": 734
                          },
                          {
                            "level": "scaffold",
                            "count": 26118
                          },
                          {
                            "level": "contig",
                            "count": 356055
                          }
                        ],
                        "rec_genome_counts": [
                          {
                            "level": "complete",
                            "count": 7793
                          },
                          {
                            "level": "chromosome",
                            "count": 759
                          },
                          {
                            "level": "scaffold",
                            "count": 27888
                          },
                          {
                            "level": "contig",
                            "count": 362877
                          }
                        ],
                        "images": [
                          {
                            "id": 70910,
                            "url": "http://www.ncbi.nlm.nih.gov/Taxonomy/taxi/images/4591",
                            "attribution": ""
                          }
                        ]
                      },
                      {
                        "tax_id": 9606,
                        "parent": 9605,
                        "is_leaf": false,
                        "name": "Homo sapiens",
                        "common_name": "human",
                        "rank": "species",
                        "raw_genome_counts": [
                          {
                            "level": "complete",
                            "count": 3
                          },
                          {
                            "level": "chromosome",
                            "count": 1173
                          },
                          {
                            "level": "scaffold",
                            "count": 978
                          },
                          {
                            "level": "contig",
                            "count": 410
                          }
                        ],
                        "rec_genome_counts": [
                          {
                            "level": "complete",
                            "count": 3
                          },
                          {
                            "level": "chromosome",
                            "count": 1173
                          },
                          {
                            "level": "scaffold",
                            "count": 978
                          },
                          {
                            "level": "contig",
                            "count": 410
                          }
                        ],
                        "images": [
                          {
                            "id": 64784,
                            "url": "http://www.ncbi.nlm.nih.gov/Taxonomy/taxi/images/422",
                            "attribution": "All of Us Initiative"
                          }
                        ]
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Missing required parameter."
          }
        },
        "operationId": "get-taxa-info",
        "description": "Get broad information of taxa filtered by their IDs",
        "parameters": [
          {
            "schema": {
              "type": "array",
              "example": [
                562,
                9606
              ],
              "items": {
                "type": "integer"
              }
            },
            "in": "query",
            "name": "taxon_ids",
            "description": "IDs of taxa to filter for",
            "explode": false,
            "style": "form",
            "required": true
          },
          {
            "$ref": "#/components/parameters/page"
          },
          {
            "$ref": "#/components/parameters/page_size"
          }
        ]
      }
    },
    "/taxa-names": {
      "get": {
        "summary": "Get taxa and their names",
        "tags": [
          "Taxon"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/TaxonName"
                  }
                },
                "examples": {
                  "Example": {
                    "value": [
                      {
                        "tax_id": 9606,
                        "name": "Homo sapiens",
                        "common_name": "human"
                      },
                      {
                        "tax_id": 9605,
                        "name": "Homo",
                        "common_name": ""
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Missing required parameter."
          }
        },
        "operationId": "get-taxa-names",
        "description": "Get taxa and their scientific and common names filtered by taxon IDs",
        "parameters": [
          {
            "schema": {
              "type": "array",
              "example": [
                9606,
                9605
              ],
              "items": {
                "type": "integer"
              }
            },
            "in": "query",
            "name": "taxon_ids",
            "description": "IDs of taxa to filter for",
            "explode": false,
            "style": "form",
            "required": true
          },
          {
            "$ref": "#/components/parameters/page"
          },
          {
            "$ref": "#/components/parameters/page_size"
          }
        ]
      }
    },
    "/taxa/{start_id}/path/{end_id}": {
      "parameters": [
        {
          "schema": {
            "type": "integer",
            "example": 9606
          },
          "name": "start_id",
          "in": "path",
          "required": true,
          "description": "id of start taxon, further from root"
        },
        {
          "schema": {
            "type": "integer",
            "example": 40674
          },
          "name": "end_id",
          "in": "path",
          "required": true,
          "description": "id of end taxon, closer to root"
        }
      ],
      "get": {
        "summary": "Get path between two taxa",
        "tags": [
          "Taxon"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Taxon"
                  }
                },
                "examples": {
                  "Example": {
                    "value": [
                      {
                        "taxid": 9606,
                        "parent": 9605,
                        "name": "Homo sapiens",
                        "common_name": "human"
                      },
                      {
                        "taxid": 9605,
                        "parent": 207598,
                        "name": "Homo",
                        "common_name": ""
                      },
                      {
                        "taxid": 207598,
                        "parent": 9604,
                        "name": "Homininae",
                        "common_name": ""
                      },
                      {
                        "taxid": 9604,
                        "parent": 314295,
                        "name": "Hominidae",
                        "common_name": "great apes"
                      },
                      {
                        "taxid": 314295,
                        "parent": 9526,
                        "name": "Hominoidea",
                        "common_name": "apes"
                      },
                      {
                        "taxid": 9526,
                        "parent": 314293,
                        "name": "Catarrhini",
                        "common_name": ""
                      },
                      {
                        "taxid": 314293,
                        "parent": 376913,
                        "name": "Simiiformes",
                        "common_name": ""
                      },
                      {
                        "taxid": 376913,
                        "parent": 9443,
                        "name": "Haplorrhini",
                        "common_name": ""
                      },
                      {
                        "taxid": 9443,
                        "parent": 314146,
                        "name": "Primates",
                        "common_name": "primates"
                      },
                      {
                        "taxid": 314146,
                        "parent": 1437010,
                        "name": "Euarchontoglires",
                        "common_name": ""
                      },
                      {
                        "taxid": 1437010,
                        "parent": 9347,
                        "name": "Boreoeutheria",
                        "common_name": ""
                      },
                      {
                        "taxid": 9347,
                        "parent": 32525,
                        "name": "Eutheria",
                        "common_name": "placentals"
                      },
                      {
                        "taxid": 32525,
                        "parent": 40674,
                        "name": "Theria",
                        "common_name": ""
                      },
                      {
                        "taxid": 40674,
                        "parent": 32524,
                        "name": "Mammalia",
                        "common_name": "mammals"
                      }
                    ]
                  }
                }
              }
            }
          },
          "404": {
            "description": "Can't find parameter's taxa."
          }
        },
        "operationId": "get-taxa-start-id-path-end-id",
        "description": "Get the path between a start taxon, that is further from root and an end taxon that is closer to root\nReturns an empty list if no path connects start and end",
        "parameters": [
          {
            "$ref": "#/components/parameters/page"
          },
          {
            "$ref": "#/components/parameters/page_size"
          }
        ]
      }
    },
    "/taxa/{taxon_id}/children": {
      "parameters": [
        {
          "schema": {
            "type": "integer",
            "example": 9606
          },
          "name": "taxon_id",
          "in": "path",
          "required": true,
          "description": "id of taxon"
        }
      ],
      "get": {
        "summary": "Get taxons children",
        "tags": [
          "Taxon"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/TaxonName"
                  }
                },
                "examples": {
                  "Example": {
                    "value": [
                      {
                        "taxid": 741158,
                        "name": "Homo sapiens subsp. 'Denisova'",
                        "common_name": "Denisova hominin"
                      },
                      {
                        "taxid": 63221,
                        "name": "Homo sapiens neanderthalensis",
                        "common_name": "Neandertal"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "operationId": "get-taxa-taxon-id",
        "description": "Get the children of a taxon given its id",
        "parameters": [
          {
            "$ref": "#/components/parameters/page"
          },
          {
            "$ref": "#/components/parameters/page_size"
          }
        ]
      }
    },
    "/taxa/{taxon_id}/images": {
      "parameters": [
        {
          "schema": {
            "type": "integer",
            "example": 9606
          },
          "name": "taxon_id",
          "in": "path",
          "required": true,
          "description": "id of taxon"
        }
      ],
      "get": {
        "summary": "Get taxons images",
        "tags": [
          "Taxon"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Image"
                  }
                }
              }
            }
          }
        },
        "operationId": "get-taxa-taxon-id-images",
        "description": "Get images associated with a taxon given its id",
        "parameters": [
          {
            "$ref": "#/components/parameters/page"
          },
          {
            "$ref": "#/components/parameters/page_size"
          }
        ]
      }
    },
    "/taxa/{taxon_id}/genome-count": {
      "parameters": [
        {
          "schema": {
            "type": "integer",
            "example": 562
          },
          "name": "taxon_id",
          "in": "path",
          "required": true,
          "description": "id of taxon"
        }
      ],
      "get": {
        "summary": "Get taxons genome count",
        "tags": [
          "Taxon"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/GenomeCount"
                  }
                },
                "examples": {
                  "Example": {
                    "value": [
                      {
                        "level": "complete",
                        "count": 7233
                      },
                      {
                        "level": "chromosome",
                        "count": 734
                      },
                      {
                        "level": "scaffold",
                        "count": 26118
                      },
                      {
                        "level": "contig",
                        "count": 356055
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "operationId": "get-taxa-taxon-id-genome-count",
        "description": "Get the number of genomes across all assembly levels for a specific taxon given its id",
        "parameters": [
          {
            "$ref": "#/components/parameters/page"
          },
          {
            "$ref": "#/components/parameters/page_size"
          }
        ]
      }
    },
    "/taxa/{taxon_id}/genome-count-recursive": {
      "parameters": [
        {
          "schema": {
            "type": "integer",
            "example": 562
          },
          "name": "taxon_id",
          "in": "path",
          "required": true,
          "description": "id of taxon"
        }
      ],
      "get": {
        "summary": "Get taxons genome count recursive",
        "tags": [
          "Taxon"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/GenomeCount"
                  }
                },
                "examples": {
                  "Example": {
                    "value": [
                      {
                        "level": "complete",
                        "count": 7793
                      },
                      {
                        "level": "chromosome",
                        "count": 759
                      },
                      {
                        "level": "scaffold",
                        "count": 27888
                      },
                      {
                        "level": "contig",
                        "count": 362877
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "operationId": "get-taxa-taxon-id-genome-count-recursive",
        "description": "Get the number of genomes across all assembly levels for the subtree of a taxon given its id",
        "parameters": [
          {
            "$ref": "#/components/parameters/page"
          },
          {
            "$ref": "#/components/parameters/page_size"
          }
        ]
      }
    },
    "/taxa/{taxon_id}/parent": {
      "parameters": [
        {
          "schema": {
            "type": "integer",
            "example": 9606
          },
          "name": "taxon_id",
          "in": "path",
          "required": true,
          "description": "id of taxon"
        }
      ],
      "get": {
        "summary": "Get taxons parent",
        "tags": [
          "Taxon"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TaxId"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "tax_id": 9605
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-taxa-taxon-id-parent",
        "description": "Get the parents taxon id of a given taxon"
      }
    },
    "/taxa/{taxon_id}/subtree": {
      "parameters": [
        {
          "schema": {
            "type": "integer",
            "example": 9606
          },
          "name": "taxon_id",
          "in": "path",
          "required": true,
          "description": "id of taxon"
        }
      ],
      "get": {
        "summary": "Get subtree of taxon",
        "tags": [
          "Taxon"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Taxon"
                  }
                },
                "examples": {
                  "Example": {
                    "value": [
                      {
                        "taxid": 9606,
                        "name": "Homo sapiens",
                        "common_name": "human",
                        "parent": 9605
                      },
                      {
                        "taxid": 741158,
                        "name": "Homo sapiens subsp. 'Denisova'",
                        "common_name": "Denisova hominin",
                        "parent": 9606
                      },
                      {
                        "taxid": 63221,
                        "name": "Homo sapiens neanderthalensis",
                        "common_name": "Neandertal",
                        "parent": 9606
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "operationId": "get-taxa-taxon-id-subtree",
        "description": "Get the subtree of a taxon including itself",
        "parameters": [
          {
            "$ref": "#/components/parameters/page"
          },
          {
            "$ref": "#/components/parameters/page_size"
          }
        ]
      }
    },
    "/taxa/{taxon_ids}/mrca": {
      "parameters": [
        {
          "schema": {
            "type": "array",
            "example": [
              9606,
              741158,
              63221
            ],
            "items": {
              "type": "integer"
            }
          },
          "name": "taxon_ids",
          "in": "path",
          "required": true,
          "description": "list of IDs which share a common ancestor"
        }
      ],
      "get": {
        "summary": "Get most recent common ancestor",
        "tags": [
          "Taxon"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TaxId"
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "tax_id": 9606
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-taxa-taxon-ids-mrca",
        "description": "Get the most recent common ancestor of a list of taxa"
      }
    }
  },
  "components": {
    "schemas": {
      "Accession": {
        "title": "Accession",
        "type": "object",
        "properties": {
          "accession": {
            "type": "string"
          },
          "level": {
            "type": "string"
          }
        }
      },
      "GenomeCount": {
        "title": "GenomeCount",
        "type": "object",
        "properties": {
          "level": {
            "type": "string"
          },
          "count": {
            "type": "integer"
          }
        }
      },
      "Image": {
        "title": "Image",
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "url": {
            "type": "string"
          },
          "attribution": {
            "type": "string"
          }
        }
      },
      "Rank": {
        "title": "Rank",
        "type": "object",
        "properties": {
          "tax_id": {
            "type": "integer"
          },
          "rank": {
            "type": "string"
          }
        }
      },
      "TaxonAccessions": {
        "title": "TaxonAccessions",
        "type": "object",
        "properties": {
          "tax_id": {
            "type": "integer"
          },
          "accessions": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Accession"
            }
          }
        }
      },
      "TaxId": {
        "title": "TaxId",
        "type": "object",
        "properties": {
          "tax_id": {
            "type": "integer"
          }
        }
      },
      "TaxonInfo": {
        "title": "TaxonInfo",
        "type": "object",
        "properties": {
          "tax_id": {
            "type": "integer"
          },
          "parent": {
            "type": "integer"
          },
          "is_leaf": {
            "type": "boolean"
          },
          "name": {
            "type": "string"
          },
          "common_name": {
            "type": "string"
          },
          "rank": {
            "type": "string"
          },
          "raw_genome_counts": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/GenomeCount"
            }
          },
          "rec_genome_counts": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/GenomeCount"
            }
          },
          "images": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Image"
            }
          }
        }
      },
      "Taxon": {
        "title": "Taxon",
        "type": "object",
        "properties": {
          "tax_id": {
            "type": "integer"
          },
          "parent": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "common_name": {
            "type": "string"
          }
        }
      },
      "TaxonName": {
        "title": "TaxonName",
        "type": "object",
        "properties": {
          "tax_id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "common_name": {
            "type": "string"
          }
        }
      }
    },
    "securitySchemes": {},
    "parameters": {
      "page": {
        "name": "page",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "default": 0,
          "example": 0,
          "minimum": 0
        },
        "description": "Current page",
        "style": "form"
      },
      "page_size": {
        "name": "page_size",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "minimum": -1,
          "example": 20,
          "default": -1
        },
        "description": "Amount of entries per page",
        "style": "form"
      }
    }
  }
}
